// What the city's people do, by the kind of place you meet them in. Each job has a couple of
// one-line descriptions and (sometimes) the outfit they wear, as avatar "top" numbers (see
// AVATAR_PARTS.top in lib/avatar.ts: 4 agbada, 10 football jersey, 14 blazer & tie,
// 15 suit & bow tie, 19 overalls, 20 dashiki, 22 scrubs, 23 chef's whites, 24 camo…).

export type PlaceKind =
  | "lobby"
  | "floor"
  | "office"
  | "home"
  | "roof"
  | "balloon"
  | "outdoor"
  | "club"
  | "restaurant"
  | "hotel"
  | "hospital"
  | "police"
  | "mall"
  | "market"
  | "museum"
  | "school"
  | "terminal"
  | "works"
  | "train"
  | "bus"
  | "car"
  | "boat"
  | "ferris"
  | "slide";

export type Job = { role: string; blurbs: readonly string[]; top?: readonly number[]; age?: readonly [number, number] };

const J = (role: string, blurbs: string[], top?: number[], age?: [number, number]): Job => ({ role, blurbs, top, age });

export const JOBS: Record<PlaceKind, readonly Job[]> = {
  lobby: [
    J("Receptionist", ["Knows everyone who comes in. Never tells.", "Has a smile for visitors and a stare for latecomers."], [2, 14]),
    J("Security guard", ["Has seen a lot of ghosts tonight. Says nothing.", "Guards the door like it owes them money."], [3, 24]),
    J("Courier", ["Always in a hurry, always lost.", "Has a parcel for someone called 'Mr Who'."], [0, 13]),
    J("Café owner", ["Makes the best puff-puff on the block.", "Sells coffee, tea and a lot of opinions."], [7, 23]),
    J("Cleaner", ["Finds everything people leave behind.", "Mops the same spot until it shines like a mirror."], [19]),
    J("Visitor", ["Just here to use the Wi-Fi.", "Waiting for someone who said 'I'm five minutes away' an hour ago."]),
    J("Concierge", ["Can get you anything. Anything.", "Knows a guy for every problem."], [15, 14]),
    J("Lift technician", ["Fixes the lift. Takes the stairs.", "Has been stuck in this lift twice. On purpose."], [19]),
    J("Delivery rider", ["Brings food faster than you can say 'I'm hungry'.", "Knows every shortcut in the city."], [16, 13]),
    J("POS agent", ["Runs the cash point by the door.", "Network is always 'just coming back'."], [5]),
    J("Newspaper vendor", ["Reads every paper before selling it.", "Has the headlines before the reporters do."], [9]),
    J("Florist", ["Sells roses to people who forgot a birthday.", "Every bouquet comes with free advice."], [7]),
    J("Generator repairman", ["Keeps the lights on when the grid gives up.", "Smells faintly of diesel and victory."], [19]),
    J("Estate agent", ["Will show you a 'spacious' flat the size of a shoe.", "Says 'it's negotiable' about everything."], [14]),
    J("Shoe shiner", ["Can tell your whole life story from your shoes.", "Makes old shoes look brand new."], [9]),
    J("Doorman", ["Opens doors and closes conversations.", "Says good morning at all hours."], [15]),
    J("Parking attendant", ["Waves cars in with great style.", "Has a whistle and isn't afraid to use it."], [16]),
    J("Lost tourist", ["Holding the map upside down. Confidently.", "Asked for directions three times already."]),
  ],
  floor: [
    J("Office worker", ["Pretends to work, mostly watches the hunt.", "Has 47 browser tabs open."], [2, 14]),
    J("Accountant", ["Counts mint for fun.", "Has a spreadsheet for their spreadsheets."], [14]),
    J("Designer", ["Thinks every billboard could be prettier.", "Owns nine shades of black."], [6, 12]),
    J("Intern", ["First week. Very excited about everything.", "Has made coffee for the whole floor. Twice."], [5], [18, 24]),
    J("Manager", ["In a meeting. Always in a meeting.", "Says 'let's circle back' a lot."], [14, 15]),
    J("Tenant", ["Has lived here for years and knows the gossip.", "Waters the plants in the corridor."]),
    J("Chef", ["Cooks jollof that could end any argument.", "Never measures. Never wrong."], [23]),
    J("IT support", ["Asks if you've tried turning it off and on.", "Fixes printers through fear alone."], [1, 9]),
    J("Lawyer", ["Objects to everything, even the weather.", "Reads the small print for fun."], [14, 15]),
    J("Architect", ["Sees lines and angles everywhere.", "Has opinions about this building's windows."], [6]),
    J("Call centre agent", ["Your call is important to them.", "Can talk for nine hours straight."], [2]),
    J("Tailor", ["Can sew a whole agbada in one night.", "Has pins in every pocket."], [4, 20]),
    J("Hairdresser", ["Hears every secret in the city.", "Braids faster than you can blink."], [7]),
    J("Barber", ["Gives the sharpest cuts and the hottest takes.", "Knows every football score since 1990."], [9, 10]),
    J("Dentist", ["Tells you to floss. You won't.", "Smiles a lot. Great teeth, obviously."], [22]),
    J("Teacher", ["Can silence a room with one look.", "Marks homework on the bus."], [2, 18]),
    J("Landlord", ["Comes around every month. You know why.", "Owns three buildings and one very loud voice."], [4, 20], [45, 80]),
    J("Student", ["Studying for exams. Sort of.", "Lives on noodles and hope."], [1, 17], [17, 26]),
    J("Freelancer", ["Works from anywhere with a socket.", "Has five jobs and no boss."], [1, 18]),
    J("Software developer", ["Fixes one bug, makes two more.", "Speaks fluent coffee."], [1, 0]),
    J("Content creator", ["Films everything. Even this.", "Has a ring light in their bag."], [13, 17]),
    J("Nanny", ["Has eyes in the back of their head.", "Can calm any crying baby in ten seconds."], [7]),
  ],
  office: [
    J("Office worker", ["Pretends to work, mostly watches the hunt.", "Lunch break is a lifestyle."], [2, 14]),
    J("Accountant", ["Counts mint for fun.", "Sleeps with a calculator."], [14]),
    J("CEO", ["Owns the corner office and the loudest laugh.", "Says 'synergy' without blinking."], [15, 4], [40, 70]),
    J("Personal assistant", ["Knows the boss's schedule better than the boss.", "Runs the whole place, quietly."], [14]),
    J("HR officer", ["Has a form for everything.", "Sends memos about memos."], [2]),
    J("Sales rep", ["Can sell sand in the desert.", "Has a pitch ready at all times."], [14, 5]),
    J("Data analyst", ["Has a chart for your mood.", "Thinks in percentages."], [6]),
    J("Intern", ["First week. Very excited about everything.", "Has already broken the photocopier."], [5], [18, 24]),
    J("Manager", ["In a meeting. Always in a meeting.", "Thinks emails need more exclamation marks."], [14, 15]),
    J("Security guard", ["Has seen a lot tonight. Says nothing.", "Knows who leaves early."], [3, 24]),
    J("Tea maker", ["Makes tea, hears everything.", "Runs the office gossip network."], [7], [40, 70]),
    J("IT support", ["Has fixed the Wi-Fi six times today.", "Lives in the server room."], [1]),
    J("Lawyer", ["Bills by the minute. Even for this chat.", "Objects to Mondays."], [14, 15]),
  ],
  home: [
    J("Neighbour", ["Borrowed your sugar in 2019.", "Knows when everyone comes and goes."]),
    J("Landlord", ["Rent is due. Always.", "Waters the plants at 6am sharp, loudly."], [4, 20], [45, 80]),
    J("Grandparent", ["Has a story for every occasion.", "Will feed you whether you're hungry or not."], [20, 4], [65, 95]),
    J("Retired champion", ["Was a champion at something, long ago.", "Reads the newspaper with great suspicion."], [4, 18], [65, 95]),
    J("Teenager", ["Lives in their headphones.", "Is 'busy' (playing games)."], [1, 17], [13, 19]),
    J("House help", ["Keeps the whole house running.", "Knows where everything is. Everything."], [7]),
    J("Relative visiting", ["Came for a weekend. That was a month ago.", "Has opinions about your career."], [4, 20], [40, 70]),
    J("Family friend visiting", ["Asks when you're getting married.", "Brought enough food for a village."], [20, 7], [40, 70]),
    J("Twin", ["People keep mixing them up. On purpose.", "Says the other twin did it."], [0, 9]),
    J("Gateman", ["Opens the gate with a wave and a story.", "Has a radio that only plays football."], [3, 16]),
    J("Home cook", ["Pot of soup on the fire at all times.", "Cooks for ten even when it's two."], [23, 7]),
  ],
  roof: [
    J("Photographer", ["Here for the sunset shot.", "Has taken 4,000 pictures of the same skyline."], [12, 6]),
    J("Gardener", ["Grows tomatoes on the roof.", "Talks to the plants. They listen."], [19, 18]),
    J("Stargazer", ["Counts planes and pretends they're stars.", "Named a star after their cat."], [16]),
    J("DJ", ["Testing speakers for tonight's party.", "Can feel the bass in their teeth."], [13, 1]),
    J("Pigeon keeper", ["Knows each pigeon by name.", "Thinks pigeons are smarter than people."], [18]),
    J("Satellite installer", ["Points dishes at the sky for a living.", "Gets better signal than anyone."], [19]),
    J("Yoga teacher", ["Breathes in. Breathes out. Judges your posture.", "Can stand on one leg for an hour."], [8]),
    J("Drone hobbyist", ["Flies tiny drones near the big ones.", "Has crashed into one billboard. Just one."], [1]),
    J("Kite flyer", ["Kite's been up there since noon.", "Knows exactly where the wind blows."], [0, 9]),
    J("Water tank repairman", ["Fixes leaks no one else can find.", "Has seen every rooftop in the city."], [19]),
    J("Sunbather", ["Here for the vitamin D.", "Hasn't moved in three hours."], [8]),
    J("Lifeguard", ["Watches the pool and the hunt at the same time.", "Has a whistle for everything."], [8]),
    J("Helicopter pilot", ["Waiting for a VIP who's very late.", "Has flown over every hiding spot in the city."], [3, 15]),
    J("Painter", ["Painting the skyline, one cloud at a time.", "Has paint in their hair. Permanently."], [19, 18]),
  ],
  balloon: [
    J("Balloon captain", ["Has flown over every city in the game.", "Steers with one hand, waves with the other."], [3, 16]),
    J("Tourist", ["Taking a thousand photos a minute.", "Bought the T-shirt before the ride."], [0, 9]),
    J("Honeymooner", ["Very much in love. Very loud about it.", "Just married. Will tell you how they met."], [15, 7]),
    J("Birdwatcher", ["Just spotted an eagle. Probably.", "Has binoculars for each eye."], [18]),
    J("Weather scientist", ["Measures the clouds. Seriously.", "Knows when it'll rain before the rain does."], [16]),
    J("Proposal planner", ["Helps people propose in the sky.", "Carries a spare ring, just in case."], [14]),
    J("Retired pilot", ["Has stories from forty years in the sky.", "Still salutes every plane."], [3, 15], [60, 85]),
    J("Map maker", ["Drawing the city from above.", "Has mapped every street but their own."], [18]),
    J("Nervous first-timer", ["Holding on very, very tight.", "Has asked 'is this safe?' nine times."]),
    J("Influencer", ["Going live from the sky.", "Asked the captain to fly 'more aesthetically'."], [13, 7]),
  ],
  outdoor: [
    J("Jogger", ["On lap twelve. Not tired at all.", "Runs every morning and tells everyone."], [8, 10]),
    J("Street vendor", ["Sells cold drinks and hot news.", "Has gala, chin-chin and every answer."], [9, 20]),
    J("Dog walker", ["Walks five dogs, controls none.", "Has treats in every pocket."], [16, 18]),
    J("Painter", ["Painting the city, one tree at a time.", "Sells a painting a week. Mostly to their mum."], [19]),
    J("Okada rider", ["Knows every shortcut, legal or not.", "Will get you there 'in two minutes'."], [12, 16]),
    J("Keke driver", ["Fits five people in a seat for three.", "Has the loudest horn in the city."], [5, 0]),
    J("Traffic warden", ["Waves cars around like an orchestra.", "Has a whistle and a lot of patience."], [3, 15]),
    J("Mechanic", ["Can fix anything with a spanner and a prayer.", "Has grease on their face and a smile."], [19]),
    J("Roadside barber", ["Cuts hair under an umbrella.", "Has the best gist on the street."], [9]),
    J("Fruit seller", ["Sells oranges, peeled to perfection.", "Remembers every customer's favourite."], [20, 7]),
    J("Busker", ["Plays the same three songs, beautifully.", "Takes requests. Ignores them."], [11, 18]),
    J("Skater", ["Rolling around the plaza all day.", "Has fallen 200 times. Still smiling."], [1, 17]),
    J("Footballer on a break", ["Plays five-a-side every evening.", "Dreams of playing for the national team."], [10]),
    J("Park ranger", ["Keeps the park tidy and the ducks happy.", "Knows every tree by name."], [24, 18]),
    J("Bird feeder", ["Feeds the pigeons. They follow everywhere.", "Has a bag of breadcrumbs, always."], [16], [55, 90]),
    J("Kids' party clown", ["On the way to a party. Already in costume.", "Has a balloon animal for everyone."], [9]),
    J("Fisherman", ["Hasn't caught anything since Tuesday.", "Says the big one got away. Again."], [19, 18]),
  ],
  club: [
    J("DJ", ["Drops the bass, picks it back up.", "Has one more song before closing. Always."], [13, 12]),
    J("Bouncer", ["Arms crossed since 2015.", "Your name's not on the list. Or is it?"], [12, 3]),
    J("Bartender", ["Mixes drinks and listens to problems.", "Has heard every story twice."], [2, 7]),
    J("Hype man", ["Shouts 'make some noise!' every five minutes.", "Has never been tired in their life."], [13, 10]),
    J("Dancer", ["Has been dancing since the doors opened.", "Knows every move from every video."], [8, 7]),
    J("Birthday celebrant", ["It's their birthday. They'll tell you.", "Has a crown and a sash."], [15, 7]),
    J("Promoter", ["Has a VIP table for you (for a price).", "Knows the DJ personally. Apparently."], [12, 14]),
    J("Photographer", ["Takes your picture whether you like it or not.", "Says 'one more!' a lot."], [12]),
    J("Waiter", ["Carries six drinks in one hand.", "Can hear your order over any song."], [15]),
    J("MC", ["Talks faster than the beat.", "Has a joke for every song."], [15, 13]),
    J("Karaoke champion", ["Undefeated on the mic since last week.", "Sings every song like it's a final."], [9]),
    J("Big spender", ["Spraying money like it's confetti.", "Ordered the whole menu. Twice."], [4, 15]),
  ],
  restaurant: [
    J("Chef", ["Cooks jollof that could end any argument.", "Tastes everything three times."], [23]),
    J("Waiter", ["Remembers every order without writing it down.", "Recommends the most expensive thing. Always."], [15, 2]),
    J("Food critic", ["Gives stars to soups.", "Has eaten everywhere twice."], [14]),
    J("Cashier", ["Says 'your change is coming' a lot.", "Can count money with their eyes closed."], [5]),
    J("Buka owner", ["Feeds the whole street at lunchtime.", "Their stew has a fan club."], [20, 7], [35, 70]),
    J("Suya man", ["Spices so hot they glow in the dark.", "Slices meat thinner than paper."], [9, 4]),
    J("Pastry chef", ["Makes meat pies that disappear in seconds.", "Has flour on everything."], [23]),
    J("Dishwasher", ["Has washed a mountain of plates today.", "Hums while scrubbing pots."], [19]),
    J("Regular customer", ["Same table, same order, every day.", "The staff know them by name."], [4, 2]),
    J("Delivery rider", ["Bringing food to the hungry, at speed.", "Has never once been late. Allegedly."], [16, 13]),
    J("Palm wine tapper", ["Brought the freshest palm wine in town.", "Climbs trees for a living."], [20]),
    J("Nutritionist", ["Here to judge your plate.", "Ordered a salad. Is sad about it."], [6]),
    J("Kitchen porter", ["Carries sacks of rice like they're pillows.", "Knows where every spoon lives."], [19]),
  ],
  hotel: [
    J("Hotel manager", ["Smiles through everything.", "Has a master key and a calm voice."], [15]),
    J("Bellhop", ["Carries suitcases bigger than themselves.", "Knows which guests tip well."], [15]),
    J("Housekeeper", ["Folds towels into swans.", "Has seen the state of every room."], [19, 7]),
    J("Guest on holiday", ["Ordered room service. Twice.", "Asked for extra pillows and got them."], [8, 0]),
    J("Business traveller", ["Here for a conference that started yesterday.", "On three phone calls at once."], [14, 15]),
    J("Wedding guest", ["Dressed in full aso-ebi.", "Here for the jollof, not the speeches."], [4, 20]),
    J("Concierge", ["Can book you anything, even a balloon ride.", "Knows the city's secret spots."], [15]),
    J("Room service waiter", ["Has a trolley and a sense of mystery.", "Knocks very politely."], [15]),
    J("Pool lifeguard", ["Watches the pool and the hunt at once.", "Blows the whistle for fun."], [8]),
  ],
  hospital: [
    J("Nurse", ["Seen it all, still kind.", "Can find a vein in the dark."], [22]),
    J("Doctor", ["On a 30-hour shift. Still smiling.", "Writes in handwriting nobody can read."], [22, 14]),
    J("Porter", ["Pushes wheelchairs at top speed.", "Knows every corridor in the building."], [22]),
    J("Patient", ["Just here for a check-up. Very bored.", "Has a broken leg and lots of time."], [0]),
    J("Visitor", ["Brought fruit and too much gist.", "Visiting their auntie (again)."]),
    J("Pharmacist", ["Has the right pill and the right advice.", "Counts tablets in their sleep."], [22]),
    J("Ambulance driver", ["Drives fast, parks perfectly.", "Knows every pothole by name."], [22, 16]),
    J("Lab scientist", ["Has a microscope and a lot of opinions.", "Labels everything twice."], [22]),
  ],
  police: [
    J("Desk sergeant", ["Has a pen, a stamp and a lot of patience.", "Writes everything down. Slowly."], [3, 24]),
    J("Detective", ["Has a notebook full of theories.", "Thinks the bot did it. Whatever it was."], [12, 14]),
    J("Traffic officer", ["Back from directing traffic. Exhausted.", "Has a whistle and tired feet."], [3]),
    J("Witness", ["Saw everything. Remembers nothing.", "Came to report a missing goat."]),
    J("Cadet", ["First day. Very serious about it.", "Salutes everyone. Even the cleaner."], [24], [18, 24]),
    J("Dog handler", ["The dog is smarter than half the station.", "Has treats in every pocket."], [24, 16]),
  ],
  mall: [
    J("Shop assistant", ["Says 'it looks great on you' to everyone.", "Folds the same shirt all day."], [5, 2]),
    J("Shopper", ["Just looking. For four hours.", "Has bags on both arms and no money left."]),
    J("Phone repairer", ["Can fix a cracked screen in ten minutes.", "Has seen what's in your gallery. Sorry."], [1]),
    J("Mall security", ["Rides a little scooter with great pride.", "Watches the cameras and the hunt."], [3, 24]),
    J("Cinema usher", ["Has seen every film fifty times.", "Shines a torch at people on their phones."], [15]),
    J("Ice cream seller", ["Has every flavour except the one you want.", "Hands out free samples (just one)."], [9]),
    J("Cleaner", ["Mops the floor, dodges the shoppers.", "Finds mint under every bench."], [19]),
    J("Window shopper", ["Never buys. Always looks.", "Knows every price in the building."]),
    J("Fashion designer", ["Judging everyone's outfits, kindly.", "Makes clothes from leftover ankara."], [20, 7]),
  ],
  market: [
    J("Market trader", ["Sells everything from pepper to phone cases.", "Can haggle a price down to nothing."], [20, 7], [30, 75]),
    J("Trader", ["Has the best prices. Just ask.", "Calls everyone 'customer'."], [4, 20]),
    J("Porter", ["Carries loads on their head like it's nothing.", "Moves faster than the crowd."], [8, 0]),
    J("Tomato seller", ["Tomatoes so red they glow.", "Gives a free one to regulars."], [20]),
    J("Fabric seller", ["Has ankara in every colour.", "Can tell you the best fabric for any party."], [20, 4]),
    J("Meat seller", ["Sharpens knives and tells jokes.", "Knows what you'll order before you do."], [19]),
    J("Fish seller", ["Fresh fish and fresher gossip.", "Swears it was caught this morning."], [19, 20]),
    J("Phone accessory seller", ["Has a charger for every phone ever made.", "Shouts 'last price!' a lot."], [9]),
    J("Herbal medicine seller", ["Has a remedy for everything (allegedly).", "Talks very fast about leaves."], [20, 4]),
    J("Shopper", ["Comparing prices at every stall.", "Has a very long list."]),
  ],
  museum: [
    J("Tour guide", ["Knows a fact about every brick.", "Walks backwards while talking."], [14, 2]),
    J("Museum guard", ["Please don't touch the exhibits.", "Has been guarding the same statue for years."], [3, 15]),
    J("Art student", ["Sketching a statue very seriously.", "Thinks everything is a metaphor."], [6, 11]),
    J("Historian", ["Can talk about old maps for hours.", "Says 'actually' a lot."], [14, 18], [45, 80]),
    J("School trip kid", ["Lost their class. Not worried.", "Has touched the exhibits."], [5, 0], [9, 13]),
    J("Clock keeper", ["Winds the big clock every morning.", "Is never, ever late."], [14, 19], [50, 85]),
    J("Curator", ["Knows where every treasure is kept.", "Whispers even when nobody's around."], [14, 6]),
  ],
  school: [
    J("Lecturer", ["Has given the same lecture since 1998.", "Says 'any questions?' and leaves."], [14, 18], [35, 70]),
    J("Student", ["Exams next week. Panic this week.", "Lives in the library (to sleep)."], [1, 17], [17, 26]),
    J("Librarian", ["Shh.", "Knows where every book is. And who has it."], [6, 18]),
    J("Professor", ["Has three degrees and no free time.", "Grades papers with a red pen and a sigh."], [14, 15], [45, 80]),
    J("Class rep", ["Sends announcements nobody reads.", "Knows when every test is."], [5]),
    J("Exam invigilator", ["Watches like a hawk. A tired hawk.", "Has confiscated many phones."], [14]),
  ],
  terminal: [
    J("Traveller", ["Their flight is delayed. Again.", "Has been at this gate since morning."]),
    J("Ticket officer", ["Has stamped ten thousand tickets.", "Will tell you which platform. Eventually."], [14, 3]),
    J("Porter", ["Can carry four suitcases at once.", "Knows every train's mood."], [19]),
    J("Announcer", ["The voice of the speakers.", "Says 'we apologise for the delay' a lot."], [14]),
    J("Snack seller", ["Sells plantain chips to everyone waiting.", "Knows which trains are late before the board does."], [9]),
    J("Pilot", ["Between flights. Coffee in hand.", "Has seen sunrise from 30,000 feet."], [3, 15]),
    J("Cleaner", ["Keeps the concourse shining.", "Has found passports, phones and one goat."], [19]),
    J("Lost passenger", ["Looking for Gate 4 at Platform 9.", "Is about to miss something important."]),
  ],
  works: [
    J("Engineer", ["Keeps the whole thing running.", "Has a hard hat and a harder handshake."], [19, 24]),
    J("Technician", ["Twists dials nobody else understands.", "Reads gauges for fun."], [19]),
    J("Safety officer", ["Has a checklist for your checklist.", "Says 'mind your step' to everyone."], [19, 16]),
    J("Crane operator", ["Can see the whole city from the cab.", "Lifts steel like it's paper."], [19]),
    J("Welder", ["Sparks are just fireworks for workers.", "Wears dark glasses at night."], [19, 12]),
    J("Night-shift worker", ["Running on tea and willpower.", "Knows how the city sounds at 3am."], [19, 16]),
  ],
  train: [
    J("Train conductor", ["Checks tickets with great ceremony.", "Has worked this line for 20 years."], [3, 15]),
    J("Commuter", ["Same train, same seat, every day.", "Reading the same page for three stops."], [14, 2]),
    J("Snack seller", ["Walks the carriages with groundnuts and gist.", "Sells out before the third stop."], [9]),
    J("Student", ["Studying on the train. Mostly sleeping.", "Has a backpack heavier than they are."], [1], [16, 25]),
    J("Ticket inspector", ["Can spot a fake ticket from across the train.", "Has never smiled on duty."], [3]),
    J("Off-duty driver", ["Drives this train usually. Today, a passenger.", "Comments on every brake."], [3, 19]),
    J("Musician", ["Plays the guitar between stops.", "Has one song and it's long."], [11, 18]),
    J("Elder with luggage", ["Brought three bags and a goat (allegedly).", "Will offer you biscuits."], [20, 7], [65, 92]),
    J("Business commuter", ["On a phone call about 'the deal'.", "Has a briefcase they never open."], [14, 15]),
    J("Sleepy traveller", ["Asleep since the last station.", "Will wake up at exactly their stop."]),
  ],
  bus: [
    J("Bus driver", ["Drives like the road is their living room.", "Has a horn and will use it."], [5, 3]),
    J("Conductor", ["Shouts the stops with great passion.", "Always has 'no change'."], [9, 0]),
    J("Passenger", ["Squeezed in and making the best of it.", "Has an opinion about the driver's music."]),
    J("School kid", ["Late for school, not worried.", "Has a lunchbox and a lot of questions."], [5, 0], [8, 14]),
    J("Hawker", ["Sells water, gala and plantain chips through the window.", "Runs faster than the bus."], [9]),
    J("Nurse after night shift", ["Just finished a 12-hour shift.", "Will fall asleep in exactly one minute."], [22]),
    J("Market trader", ["Has three baskets and the window seat.", "Knows everyone on this route."], [20], [35, 75]),
    J("Preaching passenger", ["Says a very long blessing for the journey.", "Hopes everyone has a good day. Loudly."], [14, 4]),
    J("Phone charger seller", ["Has a power bank for everyone.", "Gives demonstrations at full volume."], [9]),
  ],
  car: [
    J("Taxi driver", ["Knows every street and every story.", "His radio only plays old hits."], [5, 2]),
    J("Ride-hail driver", ["Five stars. Asks you to rate them five stars.", "Has phone chargers for every phone."], [5, 14]),
    J("Chauffeur", ["Drives a very shiny car for a very busy boss.", "Opens doors like a ceremony."], [15]),
    J("Passenger", ["Navigating from the back seat.", "Asked 'are we there yet?' twice."]),
    J("Driving instructor", ["Has a brake on their side too. Uses it.", "Very calm. Suspiciously calm."], [5]),
    J("Mechanic on a test drive", ["Listening to the engine like it's music.", "Thinks the car is fine. Mostly."], [19]),
  ],
  boat: [
    J("Boat captain", ["Knows every wave by name.", "Has a hat that says 'Captain'."], [3, 15]),
    J("Deckhand", ["Ties knots you've never heard of.", "Has sea legs and land jokes."], [9, 8]),
    J("Fisherman", ["Caught a fish this big. Honestly.", "Smells of the sea and victory."], [19, 18]),
    J("Ferry passenger", ["Feeding the gulls, against the rules.", "Takes this ferry to work every day."]),
    J("Lifeguard", ["Watches the water like a hawk.", "Has a whistle and a float."], [8]),
    J("Tourist", ["Very excited about the water.", "Taking photos of every bird."], [0, 9]),
    J("Boat mechanic", ["Fixes engines with a spanner and a song.", "Has oil on everything."], [19]),
    J("Sailor", ["Has sailed every sea. Allegedly.", "Tells stories about mermaids."], [9, 3]),
  ],
  ferris: [
    J("Ferris wheel operator", ["Pulls the lever, watches the world go round.", "Has been round 10,000 times."], [19, 9]),
    J("Couple on a date", ["Waiting for the top to say something special.", "Very nervous. Very cute."], [15, 7]),
    J("Kid with candy floss", ["Has candy floss on their face.", "Wants to go again. And again."], [0, 9], [6, 12]),
    J("Photographer", ["Shooting the city from the top.", "Has the best angle and they know it."], [12]),
    J("Height-hating passenger", ["Hates heights. Came anyway.", "Holding on to the bar with both hands."], [4, 20], [40, 70]),
    J("Tourist", ["Wants a photo at the very top.", "Has bought three souvenirs already."], [0, 9]),
    J("Funfair worker", ["Runs the hook-a-duck stall.", "Can win any prize. Won't tell you how."], [19, 9]),
  ],
  slide: [
    J("Lifeguard", ["Watches the splash zone closely.", "Has a whistle and a sun hat."], [8]),
    J("Kid", ["On their 40th go. Not stopping.", "Thinks this is the best day ever."], [8, 0], [6, 12]),
    J("Slide operator", ["Says 'arms crossed, legs straight' all day.", "Has a very loud whistle."], [9, 19]),
    J("Daredevil", ["Went down head first. Don't.", "Has tried every slide in the city."], [8]),
    J("Parent", ["Holding everyone's shoes and bags.", "Has been 'just one more go' for an hour."]),
    J("Influencer", ["Filming the slide in slow motion.", "Did the slide six times for one video."], [13]),
  ],
};

/** How a place sounds in a sentence: "this floor", "this balloon"… */
export const PLACE_NOUN: Record<PlaceKind, readonly string[]> = {
  lobby: ["this lobby", "the ground floor", "this entrance hall"],
  floor: ["this floor", "this building", "this level"],
  office: ["this office", "this floor", "this company"],
  home: ["this house", "this flat", "this compound"],
  roof: ["this rooftop", "up here", "this roof"],
  balloon: ["this balloon", "up here in the sky", "this basket"],
  outdoor: ["this place", "out here", "this corner of the city"],
  club: ["this club", "this lounge", "the dance floor"],
  restaurant: ["this restaurant", "this kitchen", "this place"],
  hotel: ["this hotel", "this lobby", "this fancy place"],
  hospital: ["this hospital", "this ward", "this place"],
  police: ["this station", "this office", "this place"],
  mall: ["this mall", "this shop", "this place"],
  market: ["this market", "these stalls", "this place"],
  museum: ["this museum", "this gallery", "this old place"],
  school: ["this school", "this campus", "this library"],
  terminal: ["this station", "this terminal", "this hall"],
  works: ["this plant", "this site", "this place"],
  train: ["this train", "this carriage", "this line"],
  bus: ["this bus", "this route", "this seat"],
  car: ["this car", "this ride", "this traffic"],
  boat: ["this boat", "the water", "this deck"],
  ferris: ["this wheel", "this funfair", "up here"],
  slide: ["this slide", "the splash zone", "this ride"],
};
