// Jokes (a setup, then the punchline when you ask "why?") and riddles (with their answers).
// Wrong guesses for a riddle are borrowed from the other riddles' answers.

export type Joke = { setup: string; punch: string };
export type Riddle = { q: string; a: string };

export const JOKES: readonly Joke[] = [
  { setup: "Why don't ghosts ever lie?", punch: "Because you can see right through them!" },
  { setup: "Why did the jollof go to school?", punch: "To become a little more seasoned!" },
  { setup: "What do you call a hunter who can't find anyone?", punch: "A tourist with a drone!" },
  { setup: "Why did the ghost join the choir?", punch: "Because it had the best boo-ming voice!" },
  { setup: "Why did NEPA take the light?", punch: "Because they needed it more than us, apparently!" },
  { setup: "What did the drone say to the pigeon?", punch: "Stop copying my flight path!" },
  { setup: "Why was the puff-puff sad?", punch: "It felt a little empty inside!" },
  { setup: "Why did the danfo driver bring a ladder?", punch: "He heard the fares were going up!" },
  { setup: "What do you call a sleeping ghost?", punch: "A boo-nap!" },
  { setup: "Why do hunters never play cards in the city?", punch: "Too many ghosts up their sleeves!" },
  { setup: "Why did the tomato blush at the market?", punch: "It saw the salad dressing!" },
  { setup: "Why did the bot refuse to move?", punch: "It was already in its comfort zone!" },
  { setup: "What do you call a balloon that tells jokes?", punch: "A pun-flatable!" },
  { setup: "Why did the suya go to the doctor?", punch: "It was feeling a bit too spicy!" },
  { setup: "Why did the ghost hide in the fridge?", punch: "It wanted to chill out!" },
  { setup: "What's a hunter's favourite exercise?", punch: "Searching for squats!" },
  { setup: "Why don't skeletons fight each other?", punch: "They don't have the guts!" },
  { setup: "Why did the plantain break up with the yam?", punch: "It found someone sweeter!" },
  { setup: "What do you call a fake noodle?", punch: "An impasta!" },
  { setup: "Why did the keke driver go to art school?", punch: "He wanted to learn how to draw a crowd!" },
  { setup: "Why did the hunter bring a pencil?", punch: "To draw the ghosts out!" },
  { setup: "What do ghosts eat for dinner?", punch: "Spook-ghetti!" },
  { setup: "Why did the phone wear glasses?", punch: "It lost its contacts!" },
  { setup: "Why did the chicken join the band?", punch: "It had the drumsticks!" },
  { setup: "What did one wall say to the other?", punch: "I'll meet you at the corner!" },
  { setup: "Why are elevators good at jokes?", punch: "They work on many levels!" },
  { setup: "Why did the ghost go to the party?", punch: "For the boos!" },
  { setup: "Why was the maths book sad?", punch: "It had too many problems!" },
  { setup: "What do you call a lazy kangaroo?", punch: "A pouch potato!" },
  { setup: "Why did the bicycle fall over?", punch: "It was two-tired!" },
  { setup: "Why did the pigeon sit on the drone?", punch: "It wanted a free ride to the roof!" },
  { setup: "What do you call a hunter with no mint?", punch: "A ghost, basically!" },
  { setup: "Why did the egusi soup go to therapy?", punch: "Too many things were stirring inside!" },
  { setup: "Why do bees have sticky hair?", punch: "Because they use honeycombs!" },
  { setup: "What did the ocean say to the beach?", punch: "Nothing, it just waved!" },
  { setup: "Why did the clock tower get a promotion?", punch: "It was always on time!" },
  { setup: "Why do cows wear bells?", punch: "Because their horns don't work!" },
  { setup: "Why did the scarecrow win an award?", punch: "He was outstanding in his field!" },
  { setup: "What's orange and sounds like a parrot?", punch: "A carrot!" },
  { setup: "Why can't you trust atoms?", punch: "They make up everything!" },
  { setup: "Why did the Ferris wheel get tired?", punch: "It was going round in circles all day!" },
  { setup: "Why did the landlord bring a calendar?", punch: "Because rent day is his favourite holiday!" },
  { setup: "Why did the ghost become a DJ?", punch: "It loved to drop the boos!" },
  { setup: "What do you call a fish wearing a crown?", punch: "A kingfish!" },
  { setup: "Why did the generator go to school?", punch: "To get a little more power!" },
  { setup: "What do you call an alligator in a vest?", punch: "An investigator!" },
  { setup: "Why don't eggs tell jokes?", punch: "They'd crack each other up!" },
  { setup: "What did the zobo say to the chapman?", punch: "You're so fancy, I'm just red!" },
  { setup: "Why was the broom late?", punch: "It over-swept!" },
  { setup: "Why did the hunter cross the road?", punch: "To search the other tile!" },
];

export const RIDDLES: readonly Riddle[] = [
  { q: "What has keys but can't open locks?", a: "a piano" },
  { q: "What gets wetter the more it dries?", a: "a towel" },
  { q: "What has hands but can't clap?", a: "a clock" },
  { q: "What has a neck but no head?", a: "a bottle" },
  { q: "What goes up but never comes down?", a: "your age" },
  { q: "What can you catch but not throw?", a: "a cold" },
  { q: "What has many teeth but can't bite?", a: "a comb" },
  { q: "The more you take, the more you leave behind. What am I?", a: "footsteps" },
  { q: "What has one eye but can't see?", a: "a needle" },
  { q: "What runs but never walks?", a: "a river" },
  { q: "What belongs to you but others use it more than you do?", a: "your name" },
  { q: "What is full of holes but still holds water?", a: "a sponge" },
  { q: "What can travel around the world while staying in a corner?", a: "a stamp" },
  { q: "What has a head and a tail but no body?", a: "a coin" },
  { q: "What building has the most stories?", a: "a library" },
  { q: "I'm tall when I'm young and short when I'm old. What am I?", a: "a candle" },
  { q: "What can fill a room but takes up no space?", a: "light" },
  { q: "What has legs but doesn't walk?", a: "a table" },
  { q: "What comes once in a minute, twice in a moment, but never in a thousand years?", a: "the letter M" },
  { q: "What has words but never speaks?", a: "a book" },
  { q: "What kind of room has no doors or windows?", a: "a mushroom" },
  { q: "If you have me, you want to share me. If you share me, you don't have me. What am I?", a: "a secret" },
  { q: "What goes through cities and fields but never moves?", a: "a road" },
  { q: "What has an eye but can't see, and is calm in the middle of a storm?", a: "a hurricane" },
  { q: "What can you hold in your right hand but not in your left?", a: "your left hand" },
  { q: "What is always in front of you but can't be seen?", a: "the future" },
  { q: "What hides in plain sight and wins every round?", a: "a good ghost" },
  { q: "What flies without wings over the city every round?", a: "a balloon" },
  { q: "What is so fragile that saying its name breaks it?", a: "silence" },
  { q: "What has thirteen hearts but no other organs?", a: "a deck of cards" },
  { q: "What gets bigger the more you take away from it?", a: "a hole" },
  { q: "What month has 28 days?", a: "all of them" },
  { q: "What can run but never gets tired, has a mouth but never talks?", a: "a river" },
  { q: "What do you throw out when you want to use it, and take in when you're done?", a: "an anchor" },
  { q: "Where does today come before yesterday?", a: "in the dictionary" },
  { q: "What has many rings but no fingers?", a: "a telephone" },
  { q: "What is black when clean and white when dirty?", a: "a chalkboard" },
  { q: "I sell pepper but I'm not a market. I sting but I'm not a bee. What am I?", a: "a chilli" },
  { q: "What has a bed but never sleeps, and a mouth but never eats?", a: "a river" },
];
