// The room trivia question bank. Each question: the right answer first, then three wrong ones
// (the game shuffles them). Questions that change over time name the year, so they stay true.

export type TriviaCategory = "Nigeria" | "Africa" | "World" | "Music" | "Football" | "Food" | "Science" | "Fun";
export type TriviaQuestion = { cat: TriviaCategory; q: string; right: string; wrong: [string, string, string] };

const Q = (cat: TriviaCategory, q: string, right: string, wrong: [string, string, string]): TriviaQuestion => ({ cat, q, right, wrong });

export const TRIVIA: TriviaQuestion[] = [
  // ---------------------------------------------------------------- Nigeria
  Q("Nigeria", "What is the capital city of Nigeria?", "Abuja", ["Lagos", "Kano", "Ibadan"]),
  Q("Nigeria", "Which is the longest river in Nigeria?", "The Niger", ["The Benue", "The Ogun", "The Kaduna"]),
  Q("Nigeria", "In which year did Nigeria become independent?", "1960", ["1963", "1957", "1970"]),
  Q("Nigeria", "In which year did Nigeria become a republic?", "1963", ["1960", "1966", "1979"]),
  Q("Nigeria", "What are the colours of the Nigerian flag?", "Green and white", ["Green and yellow", "Red and white", "Green, white and red"]),
  Q("Nigeria", "What is Nigeria's currency called?", "Naira", ["Cedi", "Shilling", "Rand"]),
  Q("Nigeria", "Which state's slogan is \"Centre of Excellence\"?", "Lagos", ["Abuja (FCT)", "Rivers", "Enugu"]),
  Q("Nigeria", "How many states does Nigeria have?", "36", ["30", "37", "24"]),
  Q("Nigeria", "Which is the most populous country in Africa?", "Nigeria", ["Ethiopia", "Egypt", "DR Congo"]),
  Q("Nigeria", "Zuma Rock stands on the road into which city?", "Abuja", ["Kano", "Jos", "Calabar"]),
  Q("Nigeria", "Who wrote the novel \"Things Fall Apart\"?", "Chinua Achebe", ["Wole Soyinka", "Chimamanda Ngozi Adichie", "Ben Okri"]),
  Q("Nigeria", "Who was the first African to win the Nobel Prize in Literature?", "Wole Soyinka", ["Chinua Achebe", "Naguib Mahfouz", "Nadine Gordimer"]),
  Q("Nigeria", "Which city is famous for its ancient bronze sculptures?", "Benin City", ["Kano", "Abeokuta", "Owerri"]),
  Q("Nigeria", "Olumo Rock is in which city?", "Abeokuta", ["Ibadan", "Ilorin", "Akure"]),
  Q("Nigeria", "The Third Mainland Bridge is in which city?", "Lagos", ["Port Harcourt", "Abuja", "Onitsha"]),
  Q("Nigeria", "Who wrote \"Half of a Yellow Sun\"?", "Chimamanda Ngozi Adichie", ["Chinua Achebe", "Buchi Emecheta", "Flora Nwapa"]),
  Q("Nigeria", "Which festival in Osogbo honours a river goddess?", "Osun-Osogbo Festival", ["Argungu Festival", "Eyo Festival", "Durbar"]),
  Q("Nigeria", "The Argungu Festival in Kebbi State is famous for what?", "Fishing", ["Horse racing", "Masquerades", "Wrestling"]),
  Q("Nigeria", "Which state is called the \"Coal City State\"?", "Enugu", ["Kogi", "Benue", "Plateau"]),
  Q("Nigeria", "Jos is the capital of which state?", "Plateau", ["Kaduna", "Bauchi", "Nasarawa"]),
  Q("Nigeria", "Which of these is NOT one of Nigeria's three biggest languages?", "Swahili", ["Hausa", "Yoruba", "Igbo"]),
  Q("Nigeria", "What is the nickname of Nigeria's men's national football team?", "Super Eagles", ["Black Stars", "Indomitable Lions", "Bafana Bafana"]),
  Q("Nigeria", "What is the nickname of Nigeria's women's national football team?", "Super Falcons", ["Super Eagles", "Black Queens", "Banyana Banyana"]),
  Q("Nigeria", "Durbar horse parades are mostly held in which part of Nigeria?", "The north", ["The south-east", "The south-west", "The Niger Delta"]),
  Q("Nigeria", "Lagos was Nigeria's capital until which year?", "1991", ["1976", "1999", "1985"]),
  Q("Nigeria", "Yankari, in Bauchi State, is famous as a…", "Game reserve and national park", ["Waterfall", "University", "Mountain"]),
  Q("Nigeria", "What is Nigeria's film industry called?", "Nollywood", ["Hollywood", "Bollywood", "Riverwood"]),
  Q("Nigeria", "Which music legend founded the Kalakuta Republic?", "Fela Kuti", ["King Sunny Adé", "Burna Boy", "2Baba"]),
  Q("Nigeria", "Obudu Mountain Resort is in which state?", "Cross River", ["Plateau", "Taraba", "Ekiti"]),
  Q("Nigeria", "The Erin-Ijesha waterfall is in which state?", "Osun", ["Ogun", "Ondo", "Kwara"]),
  Q("Nigeria", "On which date is Nigeria's Independence Day?", "1 October", ["12 June", "27 May", "1 January"]),
  Q("Nigeria", "Since 2019, Nigeria's Democracy Day has been on which date?", "12 June", ["1 October", "29 May", "15 January"]),
  Q("Nigeria", "Which city is the capital of Rivers State?", "Port Harcourt", ["Warri", "Uyo", "Yenagoa"]),
  Q("Nigeria", "Kano is the capital of which state?", "Kano", ["Kaduna", "Katsina", "Jigawa"]),

  // ---------------------------------------------------------------- Africa
  Q("Africa", "What is the longest river in Africa?", "The Nile", ["The Congo", "The Niger", "The Zambezi"]),
  Q("Africa", "What is the largest country in Africa by area?", "Algeria", ["Nigeria", "DR Congo", "Sudan"]),
  Q("Africa", "Mount Kilimanjaro is in which country?", "Tanzania", ["Kenya", "Uganda", "Ethiopia"]),
  Q("Africa", "Victoria Falls lies between Zambia and which country?", "Zimbabwe", ["Botswana", "Mozambique", "Malawi"]),
  Q("Africa", "What is the capital of Ghana?", "Accra", ["Kumasi", "Lomé", "Tamale"]),
  Q("Africa", "What is the capital of Kenya?", "Nairobi", ["Mombasa", "Kampala", "Dodoma"]),
  Q("Africa", "The pyramids of Giza are in which country?", "Egypt", ["Sudan", "Morocco", "Libya"]),
  Q("Africa", "Nelson Mandela was president of which country?", "South Africa", ["Zimbabwe", "Namibia", "Botswana"]),
  Q("Africa", "What is the largest desert in Africa?", "The Sahara", ["The Kalahari", "The Namib", "The Danakil"]),
  Q("Africa", "Which country is called the \"Rainbow Nation\"?", "South Africa", ["Ghana", "Rwanda", "Kenya"]),
  Q("Africa", "What is Africa's largest lake?", "Lake Victoria", ["Lake Tanganyika", "Lake Chad", "Lake Malawi"]),
  Q("Africa", "The ancient city of Aksum is in which country?", "Ethiopia", ["Sudan", "Somalia", "Kenya"]),
  Q("Africa", "Timbuktu is in which country?", "Mali", ["Niger", "Senegal", "Mauritania"]),
  Q("Africa", "What is the capital of Senegal?", "Dakar", ["Bamako", "Banjul", "Conakry"]),
  Q("Africa", "Kigali is the capital of which country?", "Rwanda", ["Burundi", "Uganda", "Malawi"]),
  Q("Africa", "Swahili is most widely spoken in which part of Africa?", "East Africa", ["West Africa", "North Africa", "Central Sahara"]),
  Q("Africa", "Which island country is famous for lemurs?", "Madagascar", ["Mauritius", "Seychelles", "Comoros"]),
  Q("Africa", "Table Mountain looks over which city?", "Cape Town", ["Durban", "Johannesburg", "Pretoria"]),
  Q("Africa", "Which country is a thin strip along a river of the same name?", "The Gambia", ["Togo", "Benin", "Liberia"]),
  Q("Africa", "The Suez Canal is in which country?", "Egypt", ["Sudan", "Libya", "Tunisia"]),
  Q("Africa", "What is Ghana's currency?", "Cedi", ["Naira", "Dalasi", "Kwacha"]),
  Q("Africa", "What is the capital of Ethiopia?", "Addis Ababa", ["Asmara", "Nairobi", "Djibouti"]),
  Q("Africa", "Which country grows the most cocoa in the world?", "Côte d'Ivoire", ["Ghana", "Nigeria", "Cameroon"]),
  Q("Africa", "The African Union's headquarters is in which city?", "Addis Ababa", ["Abuja", "Johannesburg", "Cairo"]),
  Q("Africa", "How many countries are there in Africa?", "54", ["48", "60", "52"]),
  Q("Africa", "Which of these countries is in North Africa?", "Morocco", ["Ghana", "Kenya", "Angola"]),
  Q("Africa", "Liberia's capital is named after a US president. What is it?", "Monrovia", ["Freetown", "Lomé", "Porto-Novo"]),
  Q("Africa", "Porto-Novo is the official capital of which country?", "Benin", ["Togo", "Burkina Faso", "Niger"]),
  Q("Africa", "In which country is Afrikaans an official language?", "South Africa", ["Kenya", "Nigeria", "Egypt"]),
  Q("Africa", "Which country is home to the Serengeti?", "Tanzania", ["Botswana", "Nigeria", "Morocco"]),

  // ---------------------------------------------------------------- the world
  Q("World", "What is the largest ocean on Earth?", "The Pacific", ["The Atlantic", "The Indian", "The Arctic"]),
  Q("World", "How many continents are there?", "7", ["5", "6", "8"]),
  Q("World", "What is the capital of Japan?", "Tokyo", ["Kyoto", "Osaka", "Seoul"]),
  Q("World", "What is the capital of Canada?", "Ottawa", ["Toronto", "Vancouver", "Montreal"]),
  Q("World", "What is the capital of Australia?", "Canberra", ["Sydney", "Melbourne", "Perth"]),
  Q("World", "The Eiffel Tower is in which city?", "Paris", ["Rome", "London", "Madrid"]),
  Q("World", "What is the tallest mountain above sea level?", "Mount Everest", ["K2", "Kilimanjaro", "Mont Blanc"]),
  Q("World", "Since 2023, which country has the most people?", "India", ["China", "USA", "Indonesia"]),
  Q("World", "The Great Wall is in which country?", "China", ["Japan", "Mongolia", "India"]),
  Q("World", "What is the smallest country in the world?", "Vatican City", ["Monaco", "San Marino", "Malta"]),
  Q("World", "Which language has the most native speakers?", "Mandarin Chinese", ["English", "Spanish", "Hindi"]),
  Q("World", "The Statue of Liberty was a gift from which country?", "France", ["The UK", "Spain", "Italy"]),
  Q("World", "What is the capital of Brazil?", "Brasília", ["Rio de Janeiro", "São Paulo", "Salvador"]),
  Q("World", "Istanbul is in which country?", "Turkey", ["Greece", "Egypt", "Iran"]),
  Q("World", "The Taj Mahal is in which country?", "India", ["Pakistan", "Iran", "Bangladesh"]),
  Q("World", "Machu Picchu is in which country?", "Peru", ["Mexico", "Chile", "Bolivia"]),
  Q("World", "Which country has a maple leaf on its flag?", "Canada", ["USA", "Norway", "Switzerland"]),
  Q("World", "What is the longest river in South America?", "The Amazon", ["The Paraná", "The Orinoco", "The Magdalena"]),
  Q("World", "Which city hosted the 2012 Summer Olympics?", "London", ["Beijing", "Rio de Janeiro", "Tokyo"]),
  Q("World", "What is the currency of the United Kingdom?", "The pound", ["The euro", "The dollar", "The franc"]),
  Q("World", "How many days are there in a leap year?", "366", ["365", "364", "360"]),
  Q("World", "Which country is famous for tulips and windmills?", "The Netherlands", ["Denmark", "Belgium", "Sweden"]),
  Q("World", "What is the capital of Germany?", "Berlin", ["Munich", "Frankfurt", "Hamburg"]),
  Q("World", "Which ocean lies between Africa and Australia?", "The Indian Ocean", ["The Pacific", "The Atlantic", "The Arctic"]),
  Q("World", "Wild kangaroos live in which country?", "Australia", ["New Zealand", "South Africa", "Brazil"]),
  Q("World", "What is the capital of the United States?", "Washington, D.C.", ["New York", "Los Angeles", "Chicago"]),
  Q("World", "Which country is shaped like a boot?", "Italy", ["Spain", "Greece", "Portugal"]),

  // ---------------------------------------------------------------- music
  Q("Music", "Which Nigerian singer released the album \"African Giant\"?", "Burna Boy", ["Wizkid", "Davido", "Olamide"]),
  Q("Music", "Wizkid's hit \"Essence\" (2020) features which singer?", "Tems", ["Ayra Starr", "Tiwa Savage", "Yemi Alade"]),
  Q("Music", "Which Nigerian star is nicknamed \"Starboy\"?", "Wizkid", ["Davido", "Rema", "Kizz Daniel"]),
  Q("Music", "Who sang the 2022 hit \"Calm Down\"?", "Rema", ["Fireboy DML", "Asake", "CKay"]),
  Q("Music", "How many keys does a standard piano have?", "88", ["76", "100", "64"]),
  Q("Music", "How many strings does a standard guitar have?", "6", ["4", "5", "12"]),
  Q("Music", "King Sunny Adé is a legend of which music style?", "Jùjú", ["Highlife", "Fuji", "Apala"]),
  Q("Music", "Which legend is called the father of Fuji music?", "Sikiru Ayinde Barrister", ["Fela Kuti", "Osita Osadebe", "Oliver De Coque"]),
  Q("Music", "Amapiano music comes from which country?", "South Africa", ["Nigeria", "Ghana", "Kenya"]),
  Q("Music", "Highlife music started in which country?", "Ghana", ["Senegal", "Sierra Leone", "Kenya"]),
  Q("Music", "Who is known as the \"King of Pop\"?", "Michael Jackson", ["Elvis Presley", "Prince", "Usher"]),
  Q("Music", "\"Love Nwantiti\" went viral for which Nigerian singer?", "CKay", ["Joeboy", "Omah Lay", "Fireboy DML"]),
  Q("Music", "Grammy-winning singer Angélique Kidjo is from which country?", "Benin", ["Togo", "Ghana", "Cameroon"]),
  Q("Music", "Which West African drum can copy the tones of speech?", "The talking drum", ["The djembe", "The bongo", "The conga"]),
  Q("Music", "What is the name of Davido's 2023 album?", "Timeless", ["Made in Lagos", "Twice as Tall", "Love, Damini"]),
  Q("Music", "\"Made in Lagos\" (2020) is an album by…", "Wizkid", ["Burna Boy", "Davido", "Tiwa Savage"]),
  Q("Music", "Miriam Makeba, \"Mama Africa\", was from which country?", "South Africa", ["Kenya", "Nigeria", "Zimbabwe"]),
  Q("Music", "Which Nigerian singer released \"Joha\" and \"Sungba\"?", "Asake", ["Rema", "Fireboy DML", "Zinoleesky"]),
  Q("Music", "How many beats are in one bar of 4/4 time?", "4", ["3", "2", "8"]),
  Q("Music", "Who sang the 2022 hit \"Rush\"?", "Ayra Starr", ["Tems", "Simi", "Teni"]),
  Q("Music", "Burna Boy won a Grammy in 2021 for which album?", "Twice as Tall", ["African Giant", "Outside", "Love, Damini"]),
  Q("Music", "\"Ojuelegba\" is a song by…", "Wizkid", ["Olamide", "9ice", "Davido"]),
  Q("Music", "What does a DJ use to mix records?", "Turntables", ["A trumpet", "A xylophone", "An accordion"]),

  // ---------------------------------------------------------------- football
  Q("Football", "In which year did Nigeria win Olympic football gold?", "1996", ["2000", "1992", "2008"]),
  Q("Football", "How many players does each team have on the pitch?", "11", ["10", "12", "9"]),
  Q("Football", "Nigeria won the Africa Cup of Nations in 1980, 1994 and which year?", "2013", ["2004", "2000", "2019"]),
  Q("Football", "Which country won the first FIFA World Cup, in 1930?", "Uruguay", ["Brazil", "Italy", "Argentina"]),
  Q("Football", "Who won the 2022 FIFA World Cup?", "Argentina", ["France", "Croatia", "Brazil"]),
  Q("Football", "Which country hosted the 2010 FIFA World Cup?", "South Africa", ["Brazil", "Germany", "Nigeria"]),
  Q("Football", "Who scored Nigeria's first ever World Cup goal, in 1994?", "Rashidi Yekini", ["Jay-Jay Okocha", "Daniel Amokachi", "Emmanuel Amuneke"]),
  Q("Football", "Jay-Jay Okocha was a star at which English club?", "Bolton Wanderers", ["Arsenal", "Chelsea", "Everton"]),
  Q("Football", "Which Nigerian was CAF African Footballer of the Year for 2023?", "Victor Osimhen", ["Ademola Lookman", "Kelechi Iheanacho", "Wilfred Ndidi"]),
  Q("Football", "How long is a normal football match, without extra time?", "90 minutes", ["60 minutes", "80 minutes", "100 minutes"]),
  Q("Football", "Outfield players may not touch the ball with their…", "Hands and arms", ["Head", "Chest", "Knees"]),
  Q("Football", "A hat-trick is how many goals by one player in a game?", "3", ["2", "4", "5"]),
  Q("Football", "Which English club is nicknamed \"The Red Devils\"?", "Manchester United", ["Liverpool", "Arsenal", "Chelsea"]),
  Q("Football", "Lionel Messi spent most of his career at which club?", "Barcelona", ["Real Madrid", "PSG", "Inter Miami"]),
  Q("Football", "Mohamed Salah plays for which country?", "Egypt", ["Morocco", "Algeria", "Tunisia"]),
  Q("Football", "Which African team reached the 2022 World Cup semi-finals?", "Morocco", ["Senegal", "Cameroon", "Ghana"]),
  Q("Football", "How many times have Nigeria's Golden Eaglets won the U-17 World Cup?", "5", ["2", "3", "4"]),
  Q("Football", "What colour card sends a player off?", "Red", ["Yellow", "Green", "Blue"]),
  Q("Football", "The Ballon d'Or is given to the…", "Best player in the world", ["Best coach", "Best goal", "Best team"]),
  Q("Football", "Didier Drogba is a legend of which country?", "Côte d'Ivoire", ["Ghana", "Cameroon", "Senegal"]),
  Q("Football", "Samuel Eto'o played for which national team?", "Cameroon", ["Nigeria", "Gabon", "Senegal"]),
  Q("Football", "Which goalkeeper was in goal for Nigeria at the 1994 World Cup?", "Peter Rufai", ["Vincent Enyeama", "Carl Ikeme", "Austin Ejide"]),
  Q("Football", "A penalty is taken from how far from the goal line?", "11 metres", ["9 metres", "16 metres", "20 metres"]),
  Q("Football", "Who won the 2023 Africa Cup of Nations (played in early 2024)?", "Côte d'Ivoire", ["Nigeria", "Senegal", "Egypt"]),

  // ---------------------------------------------------------------- food
  Q("Food", "Which two countries famously argue about whose jollof is best?", "Nigeria and Ghana", ["Kenya and Uganda", "Egypt and Sudan", "Mali and Niger"]),
  Q("Food", "Suya is mostly made from…", "Spicy grilled meat", ["Fried fish", "Boiled yam", "Beans"]),
  Q("Food", "Egusi soup is made with ground…", "Melon seeds", ["Groundnuts", "Cassava", "Palm kernels"]),
  Q("Food", "Moi moi is made mainly from…", "Beans", ["Rice", "Corn", "Yam"]),
  Q("Food", "Akara is a fried ball made from…", "Beans", ["Plantain", "Cassava", "Wheat"]),
  Q("Food", "In Nigeria, what is \"dodo\"?", "Fried plantain", ["Fried yam", "Boiled egg", "Pepper soup"]),
  Q("Food", "Garri is made from…", "Cassava", ["Yam", "Maize", "Millet"]),
  Q("Food", "What is puff-puff?", "A sweet fried dough ball", ["A spicy soup", "A rice dish", "A drink"]),
  Q("Food", "Pounded yam is usually eaten with…", "Soup, like egusi", ["Tea", "Ice cream", "Cornflakes"]),
  Q("Food", "Zobo drink is made from which flower?", "Hibiscus", ["Rose", "Sunflower", "Jasmine"]),
  Q("Food", "Chapman is a popular Nigerian…", "Mocktail", ["Soup", "Bread", "Snack"]),
  Q("Food", "Kunu is a drink made mainly from…", "Grains like millet", ["Coconut", "Coffee", "Oranges"]),
  Q("Food", "Which country is famous for pizza and pasta?", "Italy", ["France", "Spain", "Greece"]),
  Q("Food", "Sushi comes from which country?", "Japan", ["China", "Thailand", "Korea"]),
  Q("Food", "Which fruit has its seeds on the outside?", "Strawberry", ["Mango", "Orange", "Banana"]),
  Q("Food", "Which spice makes curry yellow?", "Turmeric", ["Cinnamon", "Black pepper", "Nutmeg"]),
  Q("Food", "Ofada rice is grown in which state?", "Ogun", ["Borno", "Rivers", "Kogi"]),
  Q("Food", "Tuwo shinkafa is most popular in which part of Nigeria?", "The north", ["The south-east", "The south-west", "The Niger Delta"]),
  Q("Food", "Groundnut soup is made with…", "Peanuts", ["Cashews", "Almonds", "Walnuts"]),
  Q("Food", "Ghanaian fufu is often made from cassava and…", "Plantain", ["Rice", "Beans", "Wheat"]),
  Q("Food", "Efo riro is a soup full of…", "Leafy greens", ["Carrots", "Potatoes", "Noodles"]),
  Q("Food", "Couscous is a staple food in which region?", "North Africa", ["West Africa", "East Asia", "South America"]),
  Q("Food", "Injera, a spongy flatbread, comes from which country?", "Ethiopia", ["Morocco", "Nigeria", "South Africa"]),
  Q("Food", "Chocolate is made from which beans?", "Cocoa beans", ["Coffee beans", "Soya beans", "Green beans"]),
  Q("Food", "What is chin chin?", "A crunchy fried snack", ["A soup", "A drink", "A rice dish"]),
  Q("Food", "Bole, a Port Harcourt favourite, is roasted…", "Plantain", ["Corn", "Cassava", "Fish skin"]),

  // ---------------------------------------------------------------- science
  Q("Science", "Which planet is called the Red Planet?", "Mars", ["Venus", "Jupiter", "Saturn"]),
  Q("Science", "What is the largest planet in our solar system?", "Jupiter", ["Saturn", "Neptune", "Earth"]),
  Q("Science", "Which gas do plants take in from the air?", "Carbon dioxide", ["Oxygen", "Nitrogen", "Hydrogen"]),
  Q("Science", "At sea level, water boils at…", "100 °C", ["90 °C", "80 °C", "120 °C"]),
  Q("Science", "How many legs does a spider have?", "8", ["6", "10", "12"]),
  Q("Science", "What is H2O?", "Water", ["Salt", "Oxygen", "Sugar"]),
  Q("Science", "Which organ pumps blood around the body?", "The heart", ["The lungs", "The liver", "The brain"]),
  Q("Science", "What is the nearest star to Earth?", "The Sun", ["Polaris", "Sirius", "Alpha Centauri"]),
  Q("Science", "How many bones are in an adult human body?", "206", ["106", "306", "186"]),
  Q("Science", "What force pulls things down towards the Earth?", "Gravity", ["Magnetism", "Friction", "Electricity"]),
  Q("Science", "What is the hardest natural material?", "Diamond", ["Gold", "Iron", "Quartz"]),
  Q("Science", "What do bees make?", "Honey", ["Silk", "Butter", "Syrup"]),
  Q("Science", "What is the largest animal on Earth?", "The blue whale", ["The elephant", "The giraffe", "The whale shark"]),
  Q("Science", "Which travels faster?", "Light", ["Sound", "They're the same", "It depends on the weather"]),
  Q("Science", "How many planets are in our solar system?", "8", ["9", "7", "10"]),
  Q("Science", "Which part of a plant makes food from sunlight?", "The leaves", ["The roots", "The flowers", "The seeds"]),
  Q("Science", "What is the chemical symbol for gold?", "Au", ["Ag", "Go", "Gd"]),
  Q("Science", "Which blood cells fight germs?", "White blood cells", ["Red blood cells", "Platelets", "Plasma"]),
  Q("Science", "What do we call animals that eat only plants?", "Herbivores", ["Carnivores", "Omnivores", "Insectivores"]),
  Q("Science", "Which planet is famous for its bright rings?", "Saturn", ["Mars", "Mercury", "Venus"]),
  Q("Science", "Which gas do we need to breathe in to live?", "Oxygen", ["Carbon dioxide", "Helium", "Neon"]),
  Q("Science", "At what temperature does water freeze?", "0 °C", ["10 °C", "-10 °C", "32 °C"]),
  Q("Science", "Which animal is called the \"ship of the desert\"?", "The camel", ["The horse", "The donkey", "The elephant"]),
  Q("Science", "How long does the Moon take to go around the Earth?", "About a month", ["About a day", "About a week", "About a year"]),
  Q("Science", "Who came up with the theory of relativity?", "Albert Einstein", ["Isaac Newton", "Galileo Galilei", "Marie Curie"]),
  Q("Science", "What is the centre of an atom called?", "The nucleus", ["The electron", "The molecule", "The shell"]),
  Q("Science", "Solar panels turn sunlight into…", "Electricity", ["Water", "Sound", "Oil"]),
  Q("Science", "What is the largest organ of the human body?", "The skin", ["The liver", "The heart", "The brain"]),
  Q("Science", "Our skin makes which vitamin in sunlight?", "Vitamin D", ["Vitamin C", "Vitamin A", "Vitamin B12"]),
  Q("Science", "What is the fastest land animal?", "The cheetah", ["The lion", "The horse", "The antelope"]),

  // ---------------------------------------------------------------- just for fun
  Q("Fun", "How many sides does a hexagon have?", "6", ["5", "7", "8"]),
  Q("Fun", "How many minutes are in an hour?", "60", ["100", "30", "90"]),
  Q("Fun", "Mixing blue and yellow paint makes…", "Green", ["Purple", "Orange", "Brown"]),
  Q("Fun", "Which of these is the biggest?", "A million", ["A thousand", "A hundred thousand", "Ten thousand"]),
  Q("Fun", "How many hours are in a day?", "24", ["12", "20", "36"]),
  Q("Fun", "What do hunters use in this game to scan an area?", "A drone", ["A kite", "A balloon", "A periscope"]),
];
