"use client";

// The icon for each minigame (registry entries name them, so the registry stays plain data).

import {
  Anchor,
  Apple,
  Armchair,
  ArrowDownToLine,
  BicepsFlexed,
  Bike,
  Bird,
  BrickWall,
  Building,
  Building2,
  Cable,
  Car,
  CarTaxiFront,
  Cctv,
  ChefHat,
  CircleDot,
  CircleHelp,
  Club,
  Copy,
  Cpu,
  Crosshair,
  Crown,
  Diamond,
  Dice3,
  Dice5,
  Disc,
  Drama,
  Drum,
  Dumbbell,
  Fence,
  Fingerprint,
  Fish,
  Flag,
  Flame,
  Flashlight,
  Footprints,
  Gem,
  Gift,
  GlassWater,
  Goal,
  Grid2x2,
  Grid3x3,
  Hammer,
  Hand,
  HandCoins,
  Hash,
  KeyRound,
  Layers,
  LayoutGrid,
  LockKeyhole,
  Map,
  MessageCircleQuestion,
  Mic,
  Mountain,
  MoveRight,
  MoveUp,
  MoveUpRight,
  Music,
  Package,
  Pencil,
  RectangleVertical,
  Rocket,
  Sailboat,
  Scissors,
  Shapes,
  Ship,
  Shirt,
  Siren,
  Spade,
  Spline,
  Swords,
  Target,
  Triangle,
  Trophy,
  Vault,
  Volleyball,
  Wallet,
  Waves,
  WholeWord,
  Zap,
  Gamepad2,
  type LucideIcon,
} from "lucide-react";
import { createElement } from "react";

const ICONS: Record<string, LucideIcon> = { Anchor, Apple, Armchair, ArrowDownToLine, BicepsFlexed, Bike, Bird, BrickWall, Building, Building2, Cable, Car, CarTaxiFront, Cctv, ChefHat, CircleDot, CircleHelp, Club, Copy, Cpu, Crosshair, Crown, Diamond, Dice3, Dice5, Disc, Drama, Drum, Dumbbell, Fence, Fingerprint, Fish, Flag, Flame, Flashlight, Footprints, Gem, Gift, GlassWater, Goal, Grid2x2, Grid3x3, Hammer, Hand, HandCoins, Hash, KeyRound, Layers, LayoutGrid, LockKeyhole, Map, MessageCircleQuestion, Mic, Mountain, MoveRight, MoveUp, MoveUpRight, Music, Package, Pencil, RectangleVertical, Rocket, Sailboat, Scissors, Shapes, Ship, Shirt, Siren, Spade, Spline, Swords, Target, Triangle, Trophy, Vault, Volleyball, Wallet, Waves, WholeWord, Zap };

/** A game's icon (a game controller if it has none). */
export const gameIcon = (name: string): LucideIcon => ICONS[name] ?? Gamepad2;

/** A game's icon as an element (the icon is picked by name, so it's made with createElement). */
export function GameIcon({ name, className }: { name: string; className?: string }) {
  return createElement(gameIcon(name), { className });
}
